#!/usr/bin/env bash

# Actual script directory path
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Process ID
PID=`ps -aux | grep -e "[A]nti_Join2Spam_Bot.py" | awk 'FNR == 1 {print $2}'`

if [ ! -z "$PID" ]; then
    echo "Already running."
    exit 1
fi

nohup python3 -u $DIR/Anti_Join2Spam_Bot.py >> $DIR/output.log 2>&1 &
echo "Starting Script..."
sleep 1
$DIR/status

exit 0
